### ISSUE TITLE
There was an error creating your ballot. Please try again later.

### ISSUE THREAD

**Issue by MRANASSPRO** [blockballot/blockballot#229]
stuck in createpoll page, after clicking "Deploy" , it generates this error: "There was an error creating your ballot. Please try again later", please solve this and make the poll easier to create

**Comment by arvind1705** [comment]
It works fine. You have to synchronize the node completely to create election.

**Comment by MRANASSPRO** [comment]
@arvind1705 what about "Add Ballot Options" ? which options you have to enter ?

**Comment by arvind1705** [comment]
@MRANASSPRO Add anything you want. It won't matter.

**Comment by MRANASSPRO** [comment]
@arvind1705 should I try it locally on my machine ?  because online it´s not working for me

**Comment by arvind1705** [comment]
@MRANASSPRO Yes, Try locally. Online it's not working maybe because of two reasons. Node is not synchronized or account does not enough ether to create the contract.

**Comment by evalineBai** [comment]
Hi sorry for the late response @MRANASSPRO and @arvind1705 , the geth server hosted in our digital ocean droplet wasn't synced fully so I had to re-sync the server and the app should be working now. I will also create an issue to find a more permanent solution for this.
